# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hhs7m-9BLRfLZ3Isgsg7HNzxyZX9uVvz
"""

!pip install langchain_openai

import os
import json
from getpass import getpass
from openai import OpenAI

