# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hhs7m-9BLRfLZ3Isgsg7HNzxyZX9uVvz
"""

import os
import json
from getpass import getpass
from openai import OpenAI
from bs4 import BeautifulSoup
import requests
from IPython.display import Markdown, display, update_display
from google.colab import userdata
import google.generativeai as genai
import gradio as gr

# Some imports for handling images
import base64
from io import BytesIO
from PIL import Image
