# -*- coding: utf-8 -*-
"""weekly_codes.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRYM0fvVXd1FbMhX1j6CKY6HLfInzCIG
"""

from google.colab import userdata
OPENAI_API_KEY = userdata.get('secretName')